-- Email notifications setup (run AFTER favourites.sql and notification_preferences.sql)
--
-- 1. Create a free Resend account: https://resend.com
-- 2. Create an API key in Resend → API Keys
-- 3. Deploy the edge functions from your project folder:
--      npx supabase login
--      npx supabase link --project-ref YOUR_PROJECT_REF
--      npx supabase functions deploy send-message-notification
--      npx supabase functions deploy send-report-notification
--      npx supabase functions deploy send-contact-form
--      npx supabase functions deploy send-welcome-email
-- 4. Run welcome_email.sql in the SQL Editor (tracks one welcome email per member)
-- 5. Add function secrets in Supabase Dashboard → Edge Functions → Secrets:
--      RESEND_API_KEY = your Resend API key
--      RESEND_FROM_EMAIL = Coffee Connectr <onboarding@resend.dev>
--      SITE_URL = https://www.coffeeconnectr.com
--      ADMIN_EMAIL = your-email@example.com  (optional fallback if admin profile email lookup fails)
--
-- Report notifications email all accounts with is_admin = true.
-- Welcome emails send once when a new member signs in (includes the How to Use guide).
-- If welcome emails do not arrive, check:
--   1. welcome_email.sql has been run
--   2. send-welcome-email is deployed (Edge Functions list in Supabase)
--   3. RESEND_API_KEY and RESEND_FROM_EMAIL secrets are set
--   4. Resend can send to any address (verify coffeeconnectr.com domain in Resend)
--   5. Edge Functions → send-welcome-email → Logs after a test sign-in
-- For production, verify your own domain in Resend and update RESEND_FROM_EMAIL.
--
-- SIGN-UP CONFIRMATION EMAILS (separate from welcome emails):
-- See supabase/auth_email_setup.sql for Resend SMTP + Supabase Auth URL settings.
